# Generated by Django 4.2.7 on 2023-11-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.FileField(upload_to='audio', verbose_name='track'),
        ),
    ]
